project/recipes/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField
from wtforms.validators import DataRequired


class AddRecipeForm(Form):
    """docstring for AddRecipeForm"""
    recipe_title = StringField('Recipe Title', validators=[DataRequired()])
    recipe_description = StringField('Recipe Description', validators=[DataRequired()])

project/recipes/views.py
from flask import render_template, Blueprint, redirect, url_for, request, flash
from project import db
from project.models import Recipe
from .forms import AddRecipeForm


recipes_blueprint = Blueprint('recipes', __name__)


def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


@recipes_blueprint.route('/')
def index():
    all_recipes = Recipe.query.all()
    return render_template('recipes.html', recipes=all_recipes)


@recipes_blueprint.route('/add', methods=['GET', 'POST'])
def add_recipe():
    form = AddRecipeForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_recipe = Recipe(form.recipe_title.data,
                                form.recipe_description.data)
            db.session.add(new_recipe)
            db.session.commit()
            flash('New recipe, {}, added!'.format(new_recipe.recipe_title),
                  'success')
            return redirect(url_for('recipes.index'))
        else:
            flash_errors(form)
            flash('ERROR! Recipe was not added.', 'error')
    return render_template('add_recipe.html', form=form)

project/users/views.py
#################
#### imports ####
#################

from flask import render_template, Blueprint, request, redirect, url_for, flash
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from itsdangerous import URLSafeTimedSerializer
from datetime import datetime


from .forms import RegisterForm, LoginForm, EmailForm, PasswordForm
from project import db, mail, app
from project.models import User


################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)

################
#### routes ####
################


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)

                send_confirmation_email(new_user.email)
                flash('Thanks for registering! \
                Please check your email to confirm your email address.',
                      'success')

                return redirect(url_for('recipes.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                flash('Thanks for logging in, {}'.format(current_user.email))
                return redirect(url_for('recipes.index'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')
    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token,
                                         salt='email-confirmation-salt',
                                         max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('recipes.index'))


@users_blueprint.route('/reset', methods=['GET', 'POST'])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.',
                  'success')
        else:
            flash('Your email address must be \
                confirmed before attempting a password reset.',
                  'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=['GET', 'POST'])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token,
                                                salt='password-reset-salt',
                                                max_age=3600)
    except:
        flash('The password reset links is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')


@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)


@users_blueprint.route('/password_change', methods=['GET', 'POST'])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('users.user_profile'))
    return render_template('password_change.html', form=form)

project/templates/_form_macros.html
{% macro render_field(field) %}

  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
  
{% endmacro %}


{% macro render_field_without_label(field) %}

  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
  
{% endmacro %}

project/templates/add_recipe.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
 
<div class="add-recipe">
 
<div class="page-header">
 
<h2>Add a New Recipe</h2>
 
  </div>
 
 
 
<form action="{{ url_for('recipes.add_recipe') }}" method="post">
    {{ form.csrf_token }}
	
	<dl>
      {{ render_field(form.recipe_title, placeholder="Enter Recipe Title") }}
      {{ render_field(form.recipe_description, placeholder="Enter Recipe Description") }}
    </dl>

    <button class="btn btn-sm btn-success" type="submit">Add Recipe</button>
  </form>
 
</div>
 
 
{% endblock %}

project/templates/email_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field_without_label %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Email Change</h2>
  </div>

  <p>Current Email: {{ current_user.email }}</p>
  <p>Please enter your new email address:</p>
  <form action="{{ url_for('users.user_email_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field_without_label(form.email, placeholder="Enter New Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

project/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}

Your account on Mario's Family Recipes was successfully created.<br>
Please click the link below to confirm your email address and<br>
activate your account:
 
<p>
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
</p>

<p>
--<br>
Questions? Comments? Email family.recipes.mh@gmail.com.
</p>

project/templates/email_password_reset.html
{# project/templates/email_password_reset.html #}

Your requested that the password for your Mario's Family Recipes account be reset.
Please click the link below to reset your password:

<p>
	<a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>

<p>
	--<br>
	Questions? Comments? Email family.recipes.mh@gmail.com.
</p>

project/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Marios Recipe App">
    <meta name="author" content="Mario Hinojosa">
    <title>Marios Recipe App</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>
 
<h1>Welcome to Mario's Recipe app!</h1>
 
 
 
This site describes our favorite family recipes!
 
 
<h2>Breakfast Recipes</h2>
 
 
<h2>Lunch Recipes</h2>
 
 
<h2>Dinner Recipes</h2>
 
 
<h2>Dessert Recipes</h2>
 
  </body>
</html>

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Marios Recipe App">
    <meta name="author" content="Mario Hinojosa">
    <title>Marios Recipe App</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
 
  <body>
 
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('recipes.index') }}">Mario's Recipes</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('recipes.index') }}">Public Recipes</a></li>
              <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>
              <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
            {% else %}
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
              <li><a href="{{ url_for('users.login') }}">Log In</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('users.user_profile') }}">{{current_user.email}}</a></li>
            {% else %}
              <li><a href="#">Welcome!</a></li>
            {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div class="content">

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}
 
        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}
        
        <!-- child template -->
        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>Mario Hinojosa - 2017</p>
      </div>
    </div><!-- /.container -->
     
    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

project/templates/login.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-registration">
  <div class="page-header">
    <h2>Log In</h2>
  </div>
  <form action="{{ url_for('users.login') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Log In</button>
  </form>
  <br>
  <p><em>Need an account? </em><a href="/register">Signup!!</a></p>
  <p><em>Forgot your password? </em><a href="/reset">Reset!!</a></p>

</div>

{% endblock %}

project/templates/password_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>Password Change</h2>
  </div>

  <form action="{{ url_for('users.user_password_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

project/templates/password_reset_email.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
  <div class="page-header">
    <h2>Email Address:</h2>
  </div>
  <form action="{{ url_for('users.reset') }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Enter Email Address") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Submit</button>
  </form>
</div>

{% endblock %}

project/templates/recipes.html
{% extends "layout.html" %}
{% block content %}

<div class="page-header">
  <h2>Recipes</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for recipe in recipes %}
        <tr>
          <td>{{ recipe.recipe_title }}</td>
          <td>{{ recipe.recipe_description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}  

project/templates/register.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
<div class="user-registration">
  <div class="page-header">
    <h2>Please Register Your New Account</h2>
  </div>
<form action="{{ url_for('users.register') }}" method="post">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      {{ render_field(form.confirm, placeholder="Confirm password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Create New Account</button>
  </form>
</div>
 
{% endblock %}

project/templates/reset_password_with_token.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
  <div class="page-header">
    <h2>New Password:</h2>
  </div>
  <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}

project/templates/user_profile.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>User Profile</h2>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Email Address</div>
        <div class="panel-body">{{current_user.email}}</div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Account Actions</div>
        <div class="panel-body"><a href="{{ url_for('users.user_email_change') }}">Change Email</a></div>
        <div class="panel-body"><a href="{{ url_for('users.user_password_change') }}">Change Password</a></div>
        {% if not current_user.email_confirmed %}
          <div class="panel-body"><a href="#">Resend Email Confirmation</a></div>
        {% endif %}
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Statistics</div>
        <div class="panel-body">Member since: {{ current_user.registered_on.strftime("%A %B %d, %Y") }}</div>
        {% if current_user.last_logged_in != None %}
          <div class="panel-body">Last Logged In: {{ current_user.last_logged_in.strftime("%A %B %d, %Y") }}</div>
        {% else %}
          <div class="panel-body">First time logged in. Welcome!</div>
        {% endif %}
        {% if current_user.email_confirmed %}
          <div class="panel-body">Email confirmed on: {{ current_user.email_confirmed_on.strftime("%A %B %d, %Y") }}</div>
        {% else %}
          <div class="panel-body">Email has not been confirmed!</div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}